logging:
  level:
    ROOT: INFO
    org:
      springframework:
        cloud:
          stream: DEBUG

server:
  port: 8081
  servlet:
    context-path: /api/relatorio

spring:
  application:
    name: relatorio-service
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:relatio_db
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: 'update'

app: