CREATE SCHEMA IF NOT EXISTS venda;

create table venda.tab_venda (
    id bigint generated by default as identity,
    des_produto varchar(250) not null,
    des_marca varchar(255),
    preco decimal(19,2),
    qtd integer,
    primary key (id)
    );

create table venda.tab_cliente (
    id bigint generated by default as identity,
    nome_cliente varchar(250) not null,
    primary key (id)
    );